### ISSUE TITLE
Marker löschen

### ISSUE THREAD

**Issue by Nautic** [Nautic/Gemeinsam-Fahren#11]
Der Teilnehmer erstellt irgendwo einen Marker mit identischer (!) Email wie in seinem alten Eintrag und klickt im Formular auf „Meinen Marker löschen“.
d. h. im Formular müsste noch ein Button ergänzt werden, der so heißt (Button grau mit schwarzer Schrift)
Der gelöschte Eintrag im CSV kann erhalten bleiben, aber wird nicht mehr auf der Karte angezeigt.

Der Name sollte beim Löschen kein Pflichtfeld mehr sein. Es sollte genügen, die Email identisch anzugeben.
WIchtig ist noch, dass man jeweils nur einen Marker pro Emailadresse anlegen kann.

**Comment by fx99-D** [comment]
> Der Name sollte beim Löschen kein Pflichtfeld mehr sein. Es sollte genügen, die Email identisch anzugeben.
> WIchtig ist noch, dass man jeweils nur einen Marker pro Emailadresse anlegen kann.
Ist so bereits realisiert.
