### ISSUE TITLE
Text im Formular

### ISSUE THREAD

**Issue by Nautic** [Nautic/Gemeinsam-Fahren#13]
Das Formular ist auf einer eigenen Seite/Fenster (nicht in der Karte integriert). 
Es bekommt die Überschrift: Gemeinsam Reisen

Rechts vom Formular kommt der Anleitungstext (siehe PPT).
Der Support-Link darf gerne aktiv verlinkt sein.

Änderungen im Formulartext:
Pop-up mit Bindestrich
Dein Angebot/Gesuch (statt ANgebote und Wünsche)

**Button**: Marker und Pop-up erstellen
Pop-up mit Bindestrich
erstellen nicht fett
Button grün

**Button** Abbrechen und zurück zur Karte
Abbrechen groß geschrieben
Button grau (statt rot)

**Button** Meinen Marker löschen
siehe #11 
Button grau

**Comment by fx99-D** [comment]
siehe e-mail
