### ISSUE TITLE
Popup der Teilnehmer: Hin- und Rückfahrt ohne Aufzählungspunkte

### ISSUE THREAD

**Issue by Nautic** [Nautic/Gemeinsam-Fahren#2]
alt:
* Hinfahrt
* Rückfahrt
* Bahn
* Auto biete
* Auto suche

neu:
Hinfahrt
Rückfahrt
* Bahn            (optional)
* Auto biete   (optional)
* Auto suche  (optional)

**Comment by fx99-D** [comment]
erledigt
