### ISSUE TITLE
Farbe für Kreis "Veranstaltungsort Erlangen"

### ISSUE THREAD

**Issue by Nautic** [Nautic/Gemeinsam-Fahren#8]
Die Linie des Kreises sollen in der Farbe des Logos sein: #00AA9E
Fläche ebenso, transparent wie gehabt

**Comment by fx99-D** [comment]
#00AA9E ist irgendwie grün, siehe https://derzonk.ddns.net/MFG/MFGkarteV23h.html

**Comment by fx99-D** [comment]
erledigt mit #E800E8

**Comment by Nautic** [comment]
Ja, das grün mit Nr. #00AA9E ist korrekt. Es ist das türkis aus dem Logo von Cornelia. Sie hatte sich vorgestellt, dass die Sternlinien und der Kreis um Erlangen (nicht um die Marker) in ihren Farben dargestellt wird.
